name: kapture_aio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.5
  easy_localization_loader: ^2.0.1
  easy_localization_generator: ^0.3.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  csv: ^5.1.1
  webview_flutter: ^4.7.0
  flutter_markdown: ^0.7.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/data/DCFeverRecommend.csv
    - assets/data/WeatherPhoto_updated.csv
    - .env