version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api_flask:
    build: ./api_flask/.
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
  php_api:
    build:
      context: ./api_camera/.
      args:
        ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "8083:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: camera_sql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: phpbb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "8306:3306"
volumes:
  db_data:
  pgdata: